name: Build, Test, and Publish

on:
  push:
    tags:    
      - '**'
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Grant execute permission to mvnw
        run: |
          chmod +x mvnw

      - name: Build Spring Boot JAR
        run: ./mvnw clean install
      
      - name: Set repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        
      - name: Login to GHCR 
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:latest
            ghcr.io/${{ env.REPO_NAME }}:${{ github.ref_name }}           
          labels: |
            org.opencontainers.image.title=INVENTARIO
            org.opencontainers.image.version=${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}